### Queueing API Status
GET http://localhost:5000/api/queueing/status

### Queueing API Enqueue
POST http://localhost:5000/api/queueing/enqueue/myqueue
Content-Type: application/json

{
  "value" : "Some data"
}

### Queueing API Dequeue
GET http://localhost:5000/api/queueing/dequeue/myqueue


### Queueing API Size
GET http://localhost:5000/api/queueing/size/myqueue